### ISSUE TITLE
Logger backends uses deprecated `:warn` instead of `:warning`

### ISSUE THREAD

**Issue by vkryukov** [elixir-lang/logger_backends#7]
Hello,

I noticed a small annoyance when developing a custom logger backend: a warning message about deprecated usage of `:warn` is produced. It can be illustrated by the [following code](https://github.com/vkryukov/logger_default_handler): 

```
victor@Mac ~/s/logger_default_handler (main)> mix run lib/logger_default_handler.exs
warning: the log level :warn is deprecated, use :warning instead
  (logger 1.17.3) lib/logger.ex:1178: Logger.elixir_level_to_erlang_level/1
  (logger 1.17.3) lib/logger.ex:635: Logger.compare_levels/2
  (logger_backends_sql 0.1.0) lib/logger_backends_sql.ex:122: LoggerBackends.SQL.meet_level?/2
  (logger_backends_sql 0.1.0) lib/logger_backends_sql.ex:79: LoggerBackends.SQL.handle_event/2
  (stdlib 6.1.2) gen_event.erl:1921: :gen_event.server_update/4
  (stdlib 6.1.2) gen_event.erl:1903: :gen_event.server_notify/4


11:14:19.305 [warning] This is a warning message

11:14:19.305 [error] This is an error message
You should see that unconditionally
victor@Mac ~/s/logger_default_handler (main)> 
```

The culprit is this [line](https://github.com/elixir-lang/logger_backends/blob/947b72eb0fc8b0b3ea163110d1e8fb9d5b1c2d80/lib/logger_backends/handler.ex#L120), and the fix is really a one-liner which I will do in a pull request.

**Comment by vkryukov** [comment]
Closing this as per as [per guidance](https://github.com/elixir-lang/logger_backends/pull/8#issuecomment-2651970940) from Jose.
